name: Pull request

on: pull_request

jobs:
  packer:
    name: Packer
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fix and validate Ubuntu templates
        uses: operatehappy/packer-github-actions@master
        with:
          command: fix
          arguments: -validate=true
          target: ubuntu/packer-minimal.json ubuntu/packer-full.json

      - name: Fix and validate Python templates
        uses: operatehappy/packer-github-actions@master
        with:
          command: fix
          arguments: -validate=true
          target: python/packer-minimal.json python/packer-full.json

      - name: Fix and validate Node templates
        uses: operatehappy/packer-github-actions@master
        with:
          command: fix
          arguments: -validate=true
          target: node/packer-minimal.json node/packer-full.json
